language: java
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      jdk: oraclejdk8
    - os: osx
      sudo: false
      jdk: oraclejdk8
      
before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew check
